### ISSUE TITLE
MythUtil-Channel-XMLTV-getLineup problems

### ISSUE THREAD

**Issue by bennettpeter** [garybuhrmaster/MythUtil#1]
I used this to update my channel lineup. On the whole it went well, but I did have the following problems:
1. I do not have a ChannelIcons storage group and the icons are normally in $HOME/.mythtv/channels. MythUtil-Channel-XMLTV-getLineup tries to use /channels as the place to store icons and complains that it is not writeable. I solved this by creating a storage group called ChannelIcons. I notice that new icons are stored in the storage group by the program, but existing icons are not. I am not sure where mythtv is actually getting its icons, maybe still using .mythtv/channels or something else. After clearing browser cache and removing the contents of /var/www/html/mythweb/data/tv_icons/ all the icons are now displayed correctly in both mythtv and mythweb.
2. Channels that are added or updated are being set to visible=0. Is this a bug? After I set them back to 1, all seems ok.

**Comment by garybuhrmaster** [comment]
As for (2), I think that is a bug regarding assigning 1 rather than True.  I'll do some testing of a fix.

In the case of (1), this is more complicated due to various legacy issues, the addition of the ChannelIcons storage group, and some distros choosing to use a home directly which is not writeable (even though the internal ChannelIcon storage group is ~/.mythtv/channels), and use of different users for the BE and mythtv-setup.  Some of the challenges are in the Wiki regarding channel icons.  I suspect some of this will go away when the mythweb does (in favor of the internal web service), and when mythtv-setup does (in favor of the internal web based setup).  There is another approach I had planned to look at using the DownloadFile API, but I am not sure if that will work any better (but may move the error to the BE where no one see the logs), and will require a lot more testing.

**Comment by garybuhrmaster** [comment]
I have applied a fix that uses the bindings to load the icons into what is typically the appropriate directory (using the DownloadFile service to let MythTV use the specified ChannelIcon storage group or ../.mythtv/.channels directory), (and a pull request to deal with a missed change), and applied a patch to use the boolean rather than the 1.  I believe this resolves the issue(s).  I am going to close this issue, but feel free to reopen if it does not seem to be working properly.
